spring.application.name=ohio-air-analysis
spring.autoconfigure.exclude=org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration,org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfiguration
# spring.datasource.url=jdbc:mysql://localhost:3306/${DB_HOST}
# spring.datasource.username=${DB_USERNAME}
# spring.datasource.password=${DB_PASSWORD}
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver